[package]
name = "postrust-npm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "3.1.3"
napi-derive = "3.1.2"
fst = "0.4.7"
brotli = "8.0.1"

[build-dependencies]
napi-build = "2.2.3"
