/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Get information about the loaded data */
export declare function getInfo(): string

/** Initialize the postcode data (called automatically on module load) */
export declare function init(): void

/** Lookup a postcode and house number */
export declare function lookup(postcode: string, huisnummer: number): LookupResult | null

/** Lookup multiple postcodes at once (batch operation) */
export declare function lookupBatch(queries: Array<[string, number]>): Array<LookupResult | undefined | null>

/** Result structure for postcode lookups */
export interface LookupResult {
  postcode: string
  straat: string
  huisnummer: number
  woonplaats: string
}
